shop/config/routes.rb
Rails.application.routes.draw do
  get 'controle_usuarios/index'

  devise_for :usuarios
  get '/carrinho' => 'carrinho#index'
  get '/carrinho/limpar' => 'carrinho#limparCarrinho'
  get '/carrinho/:id' => 'carrinho#add'

  resources :produtos do 
    resources :comentarios
  end  
  root 'jogos#home'

  get 'jogos/sobre'

  get 'jogos/perguntas'

  get 'jogos/contato'

end

shop/app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :produto
  belongs_to :usuario
end

shop/app/models/produto.rb
class Produto < ActiveRecord::Base
	belongs_to  :user
	has_many :comentarios

end

shop/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  enum role: [:usuario_normal, :admin]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :produtos
  has_many :comentarios       

end

shop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

shop/app/controllers/carrinho_controller.rb
class CarrinhoController < ApplicationController
  
before_action :authenticate_usuario!, except: [:index]

  def add 
  	id = params[:id]
  		if session[:carrinho] then
  			carrinho = session[:carrinho]
  		else
  			session[:carrinho] = {}
  			carrinho = session[:carrinho]
  		end
  		
  		if carrinho[id] then
  			carrinho[id] = carrinho[id] + 1
  		else
  			carrinho[id] = 1
  		end
  	redirect_to :action => :index
  end
  
  def limparCarrinho
  		session[:carrinho] = nil
  		redirect_to :action => :index
  end
						
  def index
  	if session[:carrinho] then
  		@carrinho = session[:carrinho]
  	else		
  		@carrinho = {}
  	end
  end

end

shop/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
before_action :encontrar_produto
before_action :encontrar_comentario, only: [ :destroy, :edit, :update]

	def create
		@comentario = @produto.comentarios.create(params[:comentario].permit(:content))
		@comentario.usuario_id = current_usuario.id if current_usuario
		@comentario.save

		if @comentario.save
			redirect_to produto_path(@produto)
		else
			render 'new'
		end		
	end

	def destroy
		@comentario.destroy
		redirect_to produto_path(@produto)
	end	

	def edit
	end

	def update

		if @comentario.update(params[:comentario].permit(:content))
			redirect_to produto_path(@produto)
		else
			render 'edit'
		end		
	end	

	private

	def encontrar_produto
		@produto = Produto.find(params[:produto_id])
	end

	def encontrar_comentario
		@comentario = @produto.comentarios.find(params[:id])
	end	

end

shop/app/controllers/controle_usuarios_controller.rb
class ControleUsuariosController < ApplicationController
before_action :authenticate_usuario!  

  def index
  	@usuarios = Usuario.all
  end 
end

shop/app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  before_action :authenticate_usuario!, only: [:contato]

  def home
  end

  def sobre
  end

  def perguntas
  end	

end

shop/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @comments = Comentario.where(produto_id: @produto).order("created_at DESC")
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto foi deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:titulo, :descricao, :imagem_url, :valor, :categoria, :subcategoria)
    end
end

shop/app/helpers/application_helper.rb
module ApplicationHelper
end

shop/app/helpers/carrinho_helper.rb
module CarrinhoHelper
end

shop/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

shop/app/helpers/controle_usuarios_helper.rb
module ControleUsuariosHelper
end

shop/app/helpers/jogos_helper.rb
module JogosHelper
end

shop/app/helpers/produtos_helper.rb
module ProdutosHelper
end

shop/app/views/carrinho/index.html.erb
<center><font color="white"><h1>Seu Carrinho</h1></font></center>
<br><br>
<%if @carrinho.empty? %>
	<center><p><font color="white">Seu carrinho está vazio!</font></p>
	<br>
	<%= link_to 'Produtos', produtos_path %> &emsp;
	<%= link_to 'Home', root_path %>
	
<% else %>	
	<center><%= link_to 'Limpar carrinho', carrinho_limpar_path %> &emsp;
	<%= link_to 'Finalizar Compra', carrinho_limpar_path, data: { confirm: 'Deseja mesmo Finalizar a Compra ?' } %> &emsp;
	<%= link_to 'Adicionar Novo Produto', produtos_path %></center>

<% end %>
<br>
<th><font color="white"><% total = 0 %></font></th>	
<ul>
<% @carrinho.each do | id, quantity | %>
	<center><table width="1000" border="1">
	<% produto = Produto.find_by_id(id) %>
	<tr>	
		<th width="250"><font color="white"> Título </font></th> 
		<th width="250"><font color="white"> Descrição </font></th>
		<th width="250"><font color="white"> Valor </font></th>
		<th width="250"><font color="white"> Quantidade </font></th>
	</tr>
	<tr>	
		<th><%= link_to produto.titulo, produto %></th>
		<th><p><font color="white"><%= produto.descricao %></font></p></th>
		<th><p><font color="white"><%= number_to_currency(produto.valor, :unit => 'R$') %></font><p></th>
		<th><font color="white"><p><%= quantity %></p></p></th></table>	
	<% total += quantity * produto.valor %><
<% end %>
<br>
<table width="1000" border="1">
	<th width="500"><font color="white"> Total </font></th>
	<th width="500"><font color="white"><p><%= number_to_currency(total, :unit => 'R$') %></p></font></th></tr>
</table></center>
</ul>
</center>

	

shop/app/views/comentarios/_comentario.html.erb
<% if comentario.usuario != nil %>
<table width="600" border="1">
	<tr>
	<th width="400"><p><font color="#F7820C"><%= comentario.usuario.email %></font>
	<%= comentario.content %></p></th>
	<th width="100">
	<% if ((comentario.usuario == current_usuario) || current_usuario.try(:admin?)) %>
		<%= button_to "Deletar", [comentario.produto, comentario], method: :delete, data: { confirm: "Are you sure you want to do this?"}%></th>
		<th width="100"><%= button_to "Editar", edit_produto_comentario_path(comentario.produto, comentario), :method => :get %>
	<% end %>
</th></tr></table>	
<% else %>	
	<% comentario.destroy %>
	<% $contador = @produto.comentarios.count - 1 %>
<% end %>

shop/app/views/comentarios/_form.html.erb
<% if usuario_signed_in? %>
	<%= form_for([@produto, @produto.comentarios.build]) do |f| %>
	<table width="600">
		<th width="400"><%= f.text_area :content %></th>
		<th width="200"><%= f.submit "      Comentar       "%></th>
	</table>	
	<% end %>
<% end %>	

shop/app/views/comentarios/edit.html.erb
<%= form_for([@produto, @comentario]) do |f| %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>	

shop/app/views/controle_usuarios/index.html.erb
<p id="notice"><%=notice %></p>

<% if ((@usuario == current_usuario) || current_usuario.try(:admin?)) %>

<center><h1><font color="white">Lista de Usuários</h1></font></center>
<br>
<center><table width="600" border="1">
	<thead>
		<tr>
			<th width="300"><font color="white">email</th></font>
			<th width="150"><font color="white">tipo de usuário</th></font>
			<th width="150"><font color="white">última visita</th></font>
		</tr></font>

	</thead>

	<tbody>
		<% @usuarios.each do |usuario| %>
			<tr>	
				<td><font color="white"><%= usuario.email %></td></font>
				<td><font color="white"><%= usuario.role %></td></font>
				<td><font color="white"><%= usuario.last_sign_in_at %></td></font>
			</tr>
		<%end%>
	</tbody>
</table></center>

<% end %>

shop/app/views/jogos/contato.html.erb
<h1>Jogos#contato</h1>
<p>Find me in app/views/jogos/contato.html.erb</p>

shop/app/views/jogos/home.html.erb
<p id="notice"><%= notice %></p>
<!DOCTYPE html>
<html>
<head>
<center><font color="white"><h1> Bem Vindo! </h1></font>
</head>
<br><br><br>
<body>
	<font color="#F7820C"><h1> Mais Aguardados! </h1></font>
	<br>
	<table width="1000" border="1", bordercolor="#F7820C">
		<th width="500"><%= image_tag "resident.jpg", width: 500 %></th>
		<th width="500"><font color="#F7820C"><h1> Resident Evil 7: Biohazard </h1>
		<br><br>
		<font size="5">Um dos jogos de survival horror mais famosos está de volta!</font>
		<br><br>
		<font color="red" size="3">Confira o trailer aqui: </font>
		<br>
		<a HREF="https://www.youtube.com/watch?v=uKxT3rTF1jI" TARGET="_blank" ><font color="white"> Trailer </a></th>
	</table>
		<table width="1000" border="1", bordercolor="#F7820C">
		<th width="500"><font color="#F7820C"><h1> Horizon Zero Dawn </h1>
		<br><br>
		<font size="5">Preparado para batalhar em um mundo devastado?</font>
		<br><br>
		<font color="red" size="3">Confira o trailer aqui: </font>
		<br>
		<a HREF="https://www.youtube.com/watch?v=_qER0Vtug_0" TARGET="_blank" ><font color="white"> Trailer </a></th>
		<th width="500"><%= image_tag "horizon.jpg", width: 500 %></th>
	</table>
		<table width="1000" border="1", bordercolor="#F7820C">
		<th width="500"><%= image_tag "honor.jpg", width: 500 %></th>
		<th width="500"><font color="#F7820C"><h1> For Honor </h1>
		<br><br>
		<font size="5">Samurais, Vikings ou Cavaleiros Medievais. De que lado você está?</font>
		<br><br>
		<font color="red" size="3">Confira o trailer aqui: </font>
		<br>
		<a HREF="https://www.youtube.com/watch?v=qt_hdlbRMNM" TARGET="_blank" ><font color="white"> Trailer </a></th>
	</table>
</body></center>
<br><br>
</html>

shop/app/views/jogos/perguntas.html.erb
<h1>Jogos#perguntas</h1>
<p>Find me in app/views/jogos/perguntas.html.erb</p>

shop/app/views/jogos/sobre.html.erb
<!DOCTYPE html>
<html>
<head>
<center><font color="white"><h1>Sobre o Site</h1></font>
</head>
<body>
<br>
<table width="500" border="1" bordercolor="#F7820C" ><th><font color="white"> Esse site possui o intuito de facilitar a distribuição de jogos digitais para usuários apaixonados. O site possui diferentes tipos de jogos eletrônicos para os mais variados gostos e é possível realizar a compra de vários títulos extremamente divertidos e empolgantes.
O site foi desenvolvido por dois estudandes de Engenharia de Software da Universidade de Brasília.</th><font></center></table>
<br>

<table width="500" border="1" bordercolor="#F7820C">
<th><font color="white" size="3" face="Times New Roman">
Filipe Coelho é um estudante de Engenharia de Software da Universidade de Brasília
 e jogador nas horas vagas.
 </th>
 <th width="200">
<%= image_tag "Filipe.jpg", width: 200 %>
</th></table>

<table width="500" border="1" bordercolor="#F7820C" >
<th width="200"><font color="white">
<%= image_tag "Igor.jpg", width: 200 %>
</th></font>
<th><font color="white" size="3" face="Times New Roman">
Igor Araújo é um estudante de Engenharia de Software da Universidade de Brasília
 e jogador nas horas vagas.
</th></font></center></table>
</body>
</html>

shop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav id="nav">
	<div id="jogos_nav">
		<%= image_tag "logo.png", width: 140 %> 

		<font size = "4"><%= link_to "Home", root_path %>
		<%= link_to "Produtos", produtos_path %>
		<%= link_to "Sobre", jogos_sobre_path %>
		<% if usuario_signed_in? %>
			<% if (current_usuario.try(:admin?)) %>
				<%= link_to "Controle de Usuarios", controle_usuarios_index_path %>
			<% end %>		
		<% end %></font>	
	</div>
	<br>

	<div id="entrar">	
		<% if usuario_signed_in? %>
			<font size = "4"><%= link_to "Minha Conta", edit_usuario_registration_path %>	
			<%= link_to "Sair", destroy_usuario_session_path, method: :delete %></font>
		<% else %>	
			<font size = "4"><%= link_to "Entrar", new_usuario_session_path %>
			<%= link_to "Cadastrar", new_usuario_registration_path %>
		<% end %></font>
	</div>
</nav>
	
<div id="main_wrap">	
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<%= yield %>
</div>
</body>
<br><br>
<footer class="container-fluid text-center">
  <center><font color="red"><p>Powered Filipe e Igor </a></p></font></center>
</footer>
</html>

shop/app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <font color="white"><%= f.label :titulo %><br></font>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <font color="white"><%= f.label :descrição %><br></font>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <font color="white"><%= f.label :imagem_url %><br></font>
    <%= f.text_field :imagem_url %>
  </div>
  <div class="field">
    <font color="white"><%= f.label :valor %><br></font>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <font color="white"><%= f.label :categoria %><br></font>
    <%= f.text_field :categoria %>
  </div>
  <div class="field">
    <font color="white"><%= f.label :subcategoria %><br></font>
    <%= f.text_field :subcategoria %>
  </div>
  <div class="actions">
    <%= f.submit "Cadastrar" %>
  </div>
<% end %>

shop/app/views/produtos/edit.html.erb
<br>
<center><font color="white"><h1>Editar Produto</h1></font>

<%= render 'form' %>

<%= link_to 'Mostrar', @produto %> |
<%= link_to 'Voltar', produtos_path %>
</center>

shop/app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<center><font color="white"><h1>Lista de Produtos</h1></font></center>
<br>
<center><table width="1000" border="5" bordercolor="#F7820C" bgcolor="#262626">
  <thead>
    <tr>
      <th width="300"><font color="white">Jogo</th></font>
      <th width="100"><font color="white">Titulo</th></font>
      <th width="100"><font color="white">Valor</th></font>
      <th width="100"><font color="white">Categoria</th></font>
       
    </tr>
  </thead>

  <body>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= image_tag   produto.imagem_url, width: 300 %></td>
        <td><font color="white"><center><%= produto.titulo %></center></td></font>           
        <td><font color="white"><center> R$ <%= produto.valor %></center></td></font>
        <td><font color="white"><center><%= produto.categoria %></center></td></font>
        <td><font color="white"><center><%= link_to 'Mostrar', produto %></center></td></font>
        <% if usuario_signed_in? %>
          <% if ((@usuario == current_usuario) ||  current_usuario.try(:admin?)) %>
            <td><center><%= link_to 'Editar', edit_produto_path(produto) %></center></td>
            <td><center><%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Você tem certeza?' } %></center></td>
          <% end %>
        <% end %>  
        <td><center><a href="/carrinho/<%= produto.id %>" > Adicionar ao Carrinho</a></center></td>
      </tr>
<br>
    <% end %>
  </tbody>
</table></tr></body></table>

<br>
<% if usuario_signed_in? %>
  <% if ((@usuario == current_usuario) ||  current_usuario.try(:admin?)) %>
    <%= link_to 'Novo Produto', new_produto_path %>
  <% end %>
<% end %>
<br><br><br>

shop/app/views/produtos/new.html.erb
<br>
<center><font color="white"><h1>Novo Produto</h1></font>

<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>
</center>

shop/app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>
<center><h1><font color="white">Sobre o produto</h1></font></center>
<br><br>
<p>
  <h3><font color="white">Titulo:</h3>
  <h3><%= @produto.titulo %></h3>
</p>
<table width="600" border="1" bgcolor="#F7820C">
<th>
  <%= image_tag @produto.imagem_url, width: 600 %>
</th>
</table>
<br>
<p>
<strong>Descrição:</strong>
  <%= @produto.descricao %>
</p>
<p>
  <strong>Valor: R$ </strong>
  <%= @produto.valor %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @produto.categoria %>
</p>

<p>
  <strong>Subcategoria:</strong>
  <%= @produto.subcategoria %>
</p></font>
<br>
<% if usuario_signed_in? %>
  <% if ((@usuario == current_usuario) ||  current_usuario.try(:admin?)) %>
    <%= link_to 'Editar', edit_produto_path(@produto) %> 
  <% end %>
<% end %> 
<br><br>
<font color="white"><% $contador = @produto.comentarios.count  %>
<h3><b> <%= $contador %>  Comentários: </b></h3> 
<br>
<%= render @produto.comentarios %>
<br>
<%= render "comentarios/form" %>
</font>     
<%= link_to 'Voltar', produtos_path %>
<br><br><br><br>

shop/app/views/usuarios/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>